Fix tests because of missing fiels
--- FAIL: TestAccessorWithNull (0.00s)
    accessor_test.go:66: open testdata/secret.yaml: no such file or directory
--- FAIL: TestAccessorSetRaw (0.00s)
    accessor_test.go:93: open testdata/pod.yaml: no such file or directory
--- FAIL: TestAccessor (0.00s)
    accessor_test.go:128: open testdata/pod.yaml: no such file or directory